# 1.You are given with a list of integer elements. Make a new list which will store square of elements of previous list

In [3]:
lst = list(map(int,input("Enter numbers:").split()))
ls = []
for i in lst:
    ls.append(i**2)
print(ls)

Enter numbers:1 2 3 4 5
[1, 4, 9, 16, 25]


In [4]:
lst = list(map(int,input("Enter numbers:").split()))
#lst = input("Enter the no: ").split() #this is not iterate
Square_ls = [lst**2 for lst in lst]
print(Square_ls)

Enter numbers:1 2 3 4 5 
[1, 4, 9, 16, 25]


# 2.From a list containing ints, strings and floats, make three lists to store them separately. 

In [12]:
#lst = list(input("Enter the no: ").split())
lst=[1,2, 3.33, 4.56,"Python","hello", 5, 4.3]
a =[]
b =[]
c =[]
for i in lst:
    if (type(i) == int):
         a.append(i)
    elif (type(i) == float):
         b.append(i)
    elif (type(i) == str):
         c.append(i)
print(a)
print(b)
print(c)

[1, 2, 5]
[3.33, 4.56, 4.3]
['Python', 'hello']


In [15]:
lst=[1,2, 3.33, 4.56,"Python","hello", 5, 4.3]
string_list=[]
integer_list=[]
float_list=[]
print(lst)
for i in lst:
    if isinstance(i,int):
        integer_list.append(i)
    if isinstance(i,str):
        string_list.append(i)
    if isinstance(i,float):
        float_list.append(i)
print(integer_list)
print(string_list)
print(float_list)

[1, 2, 3.33, 4.56, 'Python', 'hello', 5, 4.3]
[1, 2, 5]
['Python', 'hello']
[3.33, 4.56, 4.3]


In [5]:
from collections import defaultdict
lst=[1,2, 3.33, 4.56,"Python","hello", 5, 4.3]
d = defaultdict(list)
for x in lst:
    d[type(x)].append(x)

print(d[int])
print(d[str])
print(d[float])

[1, 2, 5]
['Python', 'hello']
[3.33, 4.56, 4.3]


# 3.	Print the pattern
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5


In [9]:
n = int(input("Enter the no:"))
for i in range(n+1):
    for j in range(1,i+1):
        print(j, end = ' ')
    print(" ")

Enter the no:5
 
1  
1 2  
1 2 3  
1 2 3 4  
1 2 3 4 5  


# 4.	Accept data in two 3*3  matrix and calculate the sum of the matrices.

In [20]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("sum of matrix = ","\n", arr + arr1)
#c=np.add(arr,arr1)
#print(c)

sum of matrix =  
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [21]:
import numpy as np
arr1 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[9, 8, 7], [6, 5, 4], [3, 2, 1]]])
#print("Array 1 : \n",arr1[0:1])
#print("Array 2 : \n",arr1[1:2])
print("sum of matrix : \n", arr1[0:1] + arr1[1:2])
#print(arr1.ndim)

sum of matrix : 
 [[[10 10 10]
  [10 10 10]
  [10 10 10]]]


In [4]:
X = [[1,2,3], 
    [4 ,5,6], 
    [7 ,8,9]] 
  
Y = [[9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]]
  
result = [[0,0,0], 
        [0,0,0], 
        [0,0,0]] 
   
for i in range(len(X)):    
    for j in range(len(Y)): 
        result[i][j] = X[i][j] + Y[i][j] 
  
print(result)
#for r in result: 
  #  print(r) 

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


# 5.Write a Python program to check whether a given number is a narcissistic number or not
For example, 371 is a narcissistic number; it has three digits, and if we cube each digits  3^3 + 7^3 + 1^3 the sum is 371. Other 3-digit narcissistic numbers are
153 = 1^3 + 5^3 + 3^3
370 = 3^3 + 7^3 + 0^3
407 = 4^3 + 0^3 + 7^3.
There are also 4-digit narcissistic numbers, some of which are 1634, 8208, 9474 since
1634 = 1^4+6^4+3^4+4^4
8208 = 8^4+2^4+0^4+8^4
9474 = 9^4+4^4+7^4+4^4



In [59]:
num = str(input("Enter the number : "))
#print(len(num))
n = int(num[0])**3 + int(num[1])**3 + int(num[2])**3
if int(num) == n:
    print("This Number Is narcissistic : ",num)

Enter the number : 153
3
This Number Is narcissistic :  153


In [65]:
num = str(input("Enter the number : "))
print(len(num))
if len(num) == 3:
    n = int(num[0])**len(num) + int(num[1])**len(num) + int(num[2])**len(num)
elif len(num) == 4:
    n = int(num[0])**len(num) + int(num[1])**len(num) + int(num[2])**len(num) + int(num[3])**len(num)
if int(num) == n:
    print("This Number Is narcissistic : ",num)

Enter the number : 1634
4
This Number Is narcissistic :  1634


In [5]:
i = input("Enter the number")
no = int(i)
num = list(map(int,str(i))) # "1,5,3"

print(num)
count = len(num)
print(count)
d = 0
for i in num:
    j = 1
    for k in range(count):
        j = j*i
    print(j)
    d += j
print(d)
if no == d:
    print("Narcissictic")
else:
    print("Not Narcissictic")

Enter the number153
[1, 5, 3]
3
1
125
27
153
Narcissictic


In [2]:
def Narci(n,p):
    temp = n
    sum = 0
    while n > 0:
        r = n % 10
        sum += r**p
        n //= 10
    print(sum)
    if sum == temp:
        return "Narcissistic number"
    else:
        return "Not Narcissistic Number"
    
n = int(input("Enter The Number"))
p = len(str(n))
print(Narci(n,p))

Enter The Number123
36
Not Narcissistic Number


In [3]:
def narc(n):
    l = len(str(n)) #convert the digit to string then find the lenght of it
    p = int(l) #typecasted to integer
    digit = [int(i) for i in str(n)]
    sum_list = [(i**p) for i in digit]
    s = sum(sum_list)
    if s==n:
        print('%d is narcissistic' %(n))
    else:
        print('%d is not narcissistic' %(n))
num = int(input('Enter the number to find it\'s narcissistic:'))
narc(num)


Enter the number to find it's narcissistic:153
153 is narcissistic
